name: siren
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  desktop_drop: ^0.7.0
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_highlighter: ^0.1.1
  flutter_markdown: ^0.7.7+1
  google_fonts: ^7.0.0
  markdown: ^7.3.0
  path: ^1.9.1
  provider: ^6.1.5+1
  webview_flutter: ^4.13.1
  webview_flutter_wkwebview: ^3.23.5
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/images/app_icon.png"
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
  android: false
  ios: false

